### ISSUE TITLE
Ceramic document links

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/specs#12]
Content links in the registry link to Ceramic tile documents.

**Comment by codynhat** [comment]
Open question here is do we want to couple the Geo Web with Ceramic?

## Why
- Allows content to be updated without ETH transactions sent by users
- Infrastructure and standards around schemas and identity
- Eventual support for NFTs to own documents
- Interoperable with much of Web3

## Why not
- Ceramic is very early in development, may block development of Geo Web
- Only JS implementation so far
- Only on test net launch
- Will this be the solution in the future?

**Comment by codynhat** [comment]
Some alternatives:
- Content identifier is an immutable IPLD object
- Link to resolver, like ENS

Both of these require transactions to be sent to the ETH blockchain whenever content needs to be changed.

**Comment by gravenp** [comment]
Per discussion on 1/12/21, moving forward with Ceramic doc integration for content linking from the Registry.

Implemented as an additional field in the Registry smart contract which contains the Ceramic doc CID.
