### ISSUE TITLE
Holding period for content changing

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/specs#17]
I've been thinking more about a specific bad case:

Someone purchases a license and pays the minimum fees (at least 2 weeks). They immediately increase the value super high, change content to something unwanted for that small period of time and never pay the license fee again. So they are willing to pay the high license fee for a small amount of time to do sort of a temporary attack.

This would be mitigated by owners not letting their fees get too low, since the buyer has to also pay the existing fees. But we could also introduce some sort of holding period for changing content. If someone snatches up a license, they must wait a certain amount of time (a few days?) before adding new content. This gives the previous owner a chance to rebuttal before someone ruins their content.

Thoughts? @gravenp

**Comment by gravenp** [comment]
We definitely need to think and work through mechanics around transfers to make that process smooth, fair, and safe. Couple threads:

- With our two week minimum fee requirement, they wouldn't be able to raise their value super high without paying two weeks at that super high rate. 
- If two weeks doesn't deter this smash-and-grab type of attack then we could always ratchet up that minimum
- Having a holding period for changing content feels off for me. If they're paying fees on the license, they should be able to exercise their rights. We could more or less enable this type of logic at the browser filtering/blocking layer though (e.g. users can decide to not load any content from an owner that purchased a land parcel within the last X days or weeks).
- If we're worried about the original owner "defending their turf" we could look at something like this [1% reclaim fee](https://ethresear.ch/t/highlight-robin-hansons-more-owner-forgiving-modified-harberger-tax/5720). 
- These additional strategies feel like post-MVP enhancements. For the simple user experiences of MVP, I think where we stand should be sufficient.

**Comment by codynhat** [comment]
Yea that makes sense for the MVP. If this becomes an issue, the first logical step is to increase the minimum fee.
