### ISSUE TITLE
Integrate initial Ceramic template fields (Parcel Name & URL) to the Cadastre

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/specs#23]
- Add Parcel Name and URL (read from linked Ceramic doc) to the parcel details window
- Graven to update mocks to account for new fields and the UX for (1) creating/linking a new doc & (2) modifying an existing doc's values

**Comment by gravenp** [comment]
@codynhat a few assumptions and questions for review before I make mocks for this:

- For this iteration, we will ONLY allow the user to populate/update the Parcel Name & URL. The user will not be able to enter an arbitrary value for the CID/Ceramic Doc. The parcel's CID value will be generated based on the inputs of the two fields. 
- We can still display the CID as a read-only field (or as a link to open the doc from IPFS in a new tab). This would be the latest CID and not the genesis record CID, right?
- Is it desirable and feasible to have the user set the Parcel Name & URL at the time of claim and transfer? Or should it require a two-step process? Existing mocks assumed the ability to set linked values at time of claim/transfer. I think this is preferable to avoid two on-chain transactions.
- URL field should be a link and default to open in a new tab. Is it feasible to include a link preview (webpage title, description, image, & domain)?
- If it is feasible to use Pinata APIs or our own mini-pinning node, then the best pinning UX is invisible on the Cadastre. When a user enters new values, we'd automatically pin the new doc for them.

**Comment by codynhat** [comment]
> We can still display the CID as a read-only field (or as a link to open the doc from IPFS in a new tab). This would be the latest CID and not the genesis record CID, right?

The CID of a Ceramic doc is actually the genesis record. But using the Ceramic protocol this can be resolved to get the latest version.

> Is it desirable and feasible to have the user set the Parcel Name & URL at the time of claim and transfer? Or should it require a two-step process? Existing mocks assumed the ability to set linked values at time of claim/transfer. I think this is preferable to avoid two on-chain transactions.

Yes, we can do it in one transaction and I think this is better as well. The owner of the license could also edit these two fields later on without needing to send a transaction. I believe if we use 3ID Connect it may ask the user to sign a message using their wallet.

> URL field should be a link and default to open in a new tab. Is it feasible to include a link preview (webpage title, description, image, & domain)?

This would be a decent amount of work for me, personally. We can try to get it in, or come back to it later.

**Comment by gravenp** [comment]
Thanks for the feedback/confirmations. I'll knock out a mockup today.

**Comment by gravenp** [comment]
See base template for "Parcel Details" and "Action Details" for initial Ceramic Integration. Also available in Figma:

<img width="1119" alt="Parcel Details - Ceramic Integrated" src="https://user-images.githubusercontent.com/15019279/104632640-408e1c80-565b-11eb-85d2-b0c4b20effcc.png">
<img width="1053" alt="Action Details - Ceramic Integrated" src="https://user-images.githubusercontent.com/15019279/104632648-43890d00-565b-11eb-9814-d389c241ced2.png">
