### ISSUE TITLE
Integrate 3ID Connect with Cadastre

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/specs#25]
Integrate [3ID Connect](https://github.com/ceramicstudio/3id-connect) with Cadastre in order to [authenticate](https://developers.ceramic.network/build/authentication/) transactions on Ceramic.

**Comment by codynhat** [comment]
@gravenp Can you let me know what you think about using [3ID Connect](https://blog.ceramic.network/what-is-3id-connect/) for authentication? Check out the [demo](https://ceramicstudio.github.io/web-playground/) too.

It appears to be the easiest way to authenticate users in order for them to publish Ceramic documents. They do not need anything else besides the blockchain wallet they already need to purchase land. But the user flow would look different.

**Comment by gravenp** [comment]
@codynhat I couldn't get the demo to work tonight, but from the that series overview this does seem like the way to go. The user flow changes amount to a just a few extra authorization transactions at setup and connect if I'm reading it right. That sounds about as straight forward as we could expect for the user and us. I'll try the demo again tomorrow though. Not sure what's going on.

**Comment by gravenp** [comment]
Confirmed the demo on Chrome and Brave. I agree this is the way to go. I'll write up a line item for this on the Help/FAQ pop-up + modify the in-panel help text as appropriate.
