### ISSUE TITLE
Dynamic or fixed land grid?

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/specs#3]
When representing land using a grid-based system (Geohash, Plus codes, etc), there are two methods to choose from:

**1. Fixed size plots of land**
- Divide the earth into a grid of fixed parts of equal size
- Every part is an NFT that can be bought/sold

**2. Dynamic size plots of land**
- Divide the earth into a nested grid
- Each NFT can be a different size depending on the length of the id

For 1), larger areas of land are represented by purchasing smaller areas in a batch. This can be done more efficiently using ERC1155. 

2) would allow a plot of land to be represented by a single NFT. But it still may require batches depending on how well the specific Geohash represents the land the buyer wants.

It seems that representing a single plot of land with a single NFT should be a design goal. For example:
- Would harberger taxes be paid by each NFT? If someone owns multiple, would they need to assign a self-assessed value and pay taxes on each separately?
- If land is listed on marketplaces like OpenSea, how would it be shown? If there are many tiny pieces of land, OpenSea would become pretty useless and only a custom marketplace would be able to properly help someone buy or sell land. Seems like this would negatively affect liquidity, and we should try to be as friendly with existing marketplaces as possible.

**Comment by codynhat** [comment]
It seems the main open question is how well will option 2 represent the land that people want? Batches may always be needed, but how often?

In general, the more people buying batches of NFTs means worse liquidity.

**Comment by gravenp** [comment]
Yeah, I think you're on the right track. Seems inevitable that land parcels will need to be able to consist of multiple Geohashes/Plus Codes/etc, but we would want them to roll up to single "entity" to make Harberger taxes and transfers feasible/manageable. Also, forced sales under the Harberger system should only be for complete parcels and not partials (if an owner wants to sell just part, they should split up their parcel accordingly).

**Comment by codynhat** [comment]
Yea good points. Thought a lot about this today. Some thoughts:
- As you mention, land will need to "roll up" in order to simplify the UX around taxes and transfers
- Because of this, the actual NFTs can be these rolled up plots of land, and not geohashes/plus codes/etc. An NFT can be a group of geohashes
- This means dynamic grids aren't really needed since the grid is not tied inherently to NFT identifiers, but are only used internally in the smart contract
- This makes lookups much simpler, assuming the grid size is appropriate granularity


Going back to our previous conversation, this would now essentially be drawing polygons, with the "thickness" of borders being the granularity of the grid. The only difference is that using Geohashes or Plus codes would have predetermined, non-overlapping slices to choose from. This makes lookups a constant time operation, instead of scaling with the number of outstanding parcels.

**Comment by codynhat** [comment]
Remaining questions:
- What is the fixed grid size?
- What happens when a user's location is less accurate (larger area) than the grid size?
