### ISSUE TITLE
Decide on fixed grid size

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/specs#4]
What is the fixed grid size? Keeping in mind:
- GPS/geolocation accuracy limits
- General future proofing

Probably < 1 m^2

**Comment by codynhat** [comment]
Looking at https://geohash.measurement.earth

A precision of 10 digits seems appropriate to start with, which is about a square meter. The areas I attempted to draw on the playground could all be represented with good accuracy.

@CodinMaster @gravenp Could you both try drawing some areas on the playground using a precision of 10 digits and see what it looks like?

**Comment by gravenp** [comment]
That's a pretty cool tool... 

Not sure if you were able to figure out a better method for "drawing" plots on that other than just clicking one at a time, but using that method, I think 10 digits seems about right. 9 is right on the edge of being too jagged for any shape other than squares/rectangles. Bumping 1 more to 10 seems appropriate to start.

Note: I think we all knew that geohashes aren't uniform in size, but this tool shows how as they get closer to the poles they are stretched North/South. Depending on how we implement initial claim fees (e.g. per geohash?), it's just something to keep in mind.

**Comment by codynhat** [comment]
Yes, that's what I did as well.

Good point. We should not make the assumption anywhere that geohashes are a fixed size.
